# Load all files from .shell/rc.d directory
if [ -d $HOME/.shellrc/rc.d ]; then
  for file in $HOME/.shellrc/rc.d/*.sh; do
    source $file || echo "Failed to source $file"
  done

  for file in $HOME/.shellrc/rc.d/*.bash; do
    source $file || echo "Failed to source $file"
  done
fi
