export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-$HOME/.cache}
# Load all files from .shell/rc.d directory
if [ -d $HOME/.shellrc/rc.d ]; then
  for file in $HOME/.shellrc/rc.d/*.sh; do
    source $file
  done

  for file in $HOME/.shellrc/zshrc.d/*.zsh; do
    source $file
  done
fi

export GPG_TTY=$(tty)
if [[ -n "$SSH_CONNECTION" ]] ;then
  export PINENTRY_USER_DATA="USE_CURSES=1"
fi

export PATH=~/.npm-global/bin:$PATH
export NODE_PATH=~/.npm-global/lib/node_modules

